title: "Chandu J S"
description: ""
sass:
  sass_dir: "assets/css" 
  style: "compressed"
include:
  - "assets"
plugins:
  - "jekyll-babel"
collections:
  works:
    output: true
    permalink: /works/:slug/
